services:
  site:
    build: "."
    ports:
      - "4000:4000" # Site
      - "35729:35729" # Live-reload
    volumes:
      - ./:/site
      - bundle_cache:/usr/local/bundle
    environment:
      - PAGES_REPO_NWO=HU-SD-S3/s3-kennisbank
volumes:
  bundle_cache: